# Generated by Django 5.0.6 on 2024-06-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Cliente',
        ),
    ]
