# Generated by Django 5.0.6 on 2024-06-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paginas', '0002_rename_usuario_cliente'),
    ]

    operations = [
    ]
