# Generated by Django 5.0.6 on 2024-07-14 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carritoFuncional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='carrito',
        ),
        migrations.AlterModelTable(
            name='product',
            table='productos',
        ),
    ]
