# Generated by Django 5.0.6 on 2024-07-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritoFuncional', '0002_alter_cart_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='imagen/'),
        ),
    ]
