# Generated by Django 5.0.6 on 2024-07-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carritoFuncional', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
