# Generated by Django 5.0.6 on 2024-07-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritoFuncional', '0005_remove_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
