# Generated by Django 5.0.6 on 2024-07-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritoFuncional', '0006_cart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='carritoFuncional/imagen/'),
        ),
    ]
