# Generated by Django 5.0.6 on 2024-06-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Productos',
        ),
    ]
