# Generated by Django 5.0.6 on 2024-07-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_rename_curso_productos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productos',
            table='productos_productos',
        ),
    ]
